export enum ATOMS {
  CURRENCY_STATE = "CURRENCY_STATE",
  SEARCH_VALUES_STATE = "SEARCH_VALUES_STATE",
}

export enum SELECTORS {
  CURRENCY_STATE_SELECTOR = "CURRENCY_STATE_SELECTOR",
  SEARCH_VALUES_STATE_SELECTOR = "SEARCH_VALUES_STATE_SELECTOR",
}
