export enum ATOMS {
  CURRENCY_STATE = "CURRENCY_STATE",
  POPULAR_DESTINATIONS = "POPULAR_DESTINATIONS",
  DRIVER_PRICES = "DRIVER_PRICES",
}

export enum SELECTORS {
  CURRENCY_STATE_SELECTOR = "CURRENCY_STATE_SELECTOR",
  POPULAR_DESTINATIONS_SELECTOR = "POPULAR_DESTINATIONS_SELECTOR",
  DRIVER_PRICES_SELECTOR = "DRIVER_PRICES_SELECTOR",
}
