name: Bump version

on:
  push:
    branches:
      - feature/ci-cd
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"

      - name: Checkout
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_SECRET_TOKEN }}
      - run: git config --global user.name 'AboutBits Tech'
      # - run: git config --global user.email 'tech@aboutbits.it'
      # - run: npm version patch -m "[RELEASE] %s"
      # - run: git push
      # - run: |
      #     git config --global user.name 'Pavel Sokolov'
      #     git config --global user.email 'pavlik.sokolov.2000@gmail.com'
      #     npm version patch -m "[RELEASE] %s"
      #     git push
