name: Bump version

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
