name: Bump version

on: [pull_request, push]

jobs:
  bump:
    runs-on: ubuntu-latest
      steps:
        - name: Git checkout
          uses: actions/checkout@v1
        - name: Branch name
          run: echo running on branch ${GITHUB_REF##*/}
        - name: Build
          run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/}
