name: Bump version

on:
  push:
    branches:
      - feature/ci-cd
  # pull_request:
  #   branches:
  #     - develop
  #   types:
  #     - closed

jobs:
  bump:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_SECRET_TOKEN }}
<<<<<<< Updated upstream
          ref: develop
=======
          fetch-depth: 0
          ref: origin/develop
>>>>>>> Stashed changes

      - name: Bump version
        run: |
          git config --global user.name 'Pavel Sokolov'
          git config --global user.email 'pavlik.sokolov.2000@gmail.com'
        if: "startsWith(steps.branch-name.outputs.current_branch, 'feature')"
        run: |
          npm version minor
          git push
        if: "!startsWith(steps.branch-name.outputs.current_branch, 'feature')"
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
          echo "commit message ${{ github.event.head_commit.message }}"
