name: Bump version

on: [pull_request, push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        if: github.event_name == 'push'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
