name: Bump version

on: [pull_request, push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      # Use branch name for whatever purpose
      - run: echo ${BRANCH_NAME}
