name: Bump version

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
