# TODO(Pavel Sokolov): Investigate npm i
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - develop
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          persist-credentials: false

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

    outputs:
      current_branch: ${{ steps.branch-name.outputs.current_branch }}

  build_and_deploy:
    needs: [prepare]

    if: needs.prepare.outputs.current_branch == 'develop' || startsWith(github.event.head_commit.message, '[RELEASE]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          persist-credentials: false

      - name: Set Dev ENVs
        if: needs.prepare.outputs.current_branch == 'develop'
        env:
          REACT_APP_API_KEY: ${{ secrets.FIREBASE_DEV_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_DEV_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_DEV_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_DEV_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_DEV_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.FIREBASE_DEV_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_DEV_MEASUREMENT_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT }}
          FIREBASE_HOSTING_TARGET: "toptrip-dev"
          FIREBASE_CONFIG_PATH: "firebase.dev.json"
        run: echo "Dev ENV-variables have been added"

      - name: Set Prod ENVs
        if: needs.prepare.outputs.current_branch == 'main'
        env:
          REACT_APP_API_KEY: ${{ secrets.FIREBASE_PROD_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_PROD_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROD_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_PROD_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_PROD_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.FIREBASE_PROD_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_PROD_MEASUREMENT_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_PROD_SERVICE_ACCOUNT }}
          FIREBASE_HOSTING_TARGET: "toptrip-prod"
        run: echo "Prod ENV-variables have been added"

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.REACT_APP_PROJECT_ID }}
          target: ${{ env.FIREBASE_HOSTING_TARGET }}
