name: Deploy to Firebase Hosting on PR

on: [pull_request]

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set ENVs
        env:
          REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.FIREBASE_DEV_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_DEV_MEASUREMENT_ID }}
        run: echo "ENV-variables have been added"

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"

      - name: Install dependencies
        run: |
          npm i

      - name: Build
        run: |
          npm run build

      - name: Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: preview
        with:
          repoToken: "${{ secrets.GH_SECRET_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Get a preview link
        run: |
          echo "${{ join(steps.preview.outputs.*, '\n') }}"
